#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# DataShuttle ClickHouse Parallel Snapshot Demo
#
# Configurable 1–3 shard ClickHouse cluster + matching DataShuttle cluster.
# DataShuttle discovers shards via system.clusters and reads each
# shard in parallel.
#
# Usage:
#   ./demo.sh up                  # 3 shards (default)
#   ./demo.sh up 1                # 1 shard (single-node, good for laptops)
#   ./demo.sh up 2                # 2 shards
#   ./demo.sh up 3                # 3 shards
#   ./demo.sh down                # stop everything, keep data
#   ./demo.sh clean               # stop + destroy all data and volumes
#   ./demo.sh status              # show what's running
#   ./demo.sh restart [shards]    # down + up [shards]
#   ./demo.sh inject              # insert 10000 events (default)
#   ./demo.sh inject 50000        # insert 50000 events
#   ./demo.sh inject sessions 200 # insert 200 sessions
#   ./demo.sh logs                # tail node-1 DataShuttle logs
#   ./demo.sh open                # open UI in browser
#
# Environment variables:
#   SHARDS=1|2|3   override shard count (default: 3)
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
OVERRIDE_FILE="$SCRIPT_DIR/.docker-compose.override.yml"

# DataShuttle node-1 is the primary API endpoint
DS_API_PORT="${DS_API_PORT:-8080}"
# ClickHouse coordinator port (node-1 HTTP)
CH_PORT="${CH_PORT:-8123}"
CH_HOST="localhost"
CH_DB="analytics"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}▸${NC} $*"; }
warn() { echo -e "${YELLOW}▸${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }
hdr()  { echo -e "\n${BOLD}${BLUE}═══ $* ═══${NC}"; }

# ── Shard count helpers ───────────────────────────────────────────────

validate_shards() {
    local n="$1"
    if [[ ! "$n" =~ ^[123]$ ]]; then
        err "SHARDS must be 1, 2, or 3 (got: $n)"
        exit 1
    fi
}

# Generate cluster-config.xml for N shards into a temp file,
# then mount it in the override. ClickHouse needs identical cluster config
# on all nodes so they can talk to each other.
generate_cluster_xml() {
    local n="$1"
    local out="$SCRIPT_DIR/.cluster-config-${n}.xml"
    {
        echo '<clickhouse>'
        echo '    <remote_servers>'
        echo '        <analytics_cluster>'
        for i in $(seq 1 "$n"); do
            echo "            <shard>"
            echo "                <replica>"
            echo "                    <host>clickhouse-${i}</host>"
            echo "                    <port>9000</port>"
            echo "                </replica>"
            echo "            </shard>"
        done
        echo '        </analytics_cluster>'
        echo '    </remote_servers>'
        echo '</clickhouse>'
    } > "$out"
    echo "$out"
}

# Write docker-compose.override.yml that:
#   1. Disables CH nodes / DS nodes beyond N
#   2. Mounts the N-shard cluster config on active CH nodes
#   3. Updates DS gossip seeds and CLUSTER_EXPECTED_NODES
generate_override() {
    local n="$1"
    local xml_file
    xml_file="$(generate_cluster_xml "$n")"
    local xml_basename
    xml_basename="$(basename "$xml_file")"

    # DS gossip seeds — each node lists all other active nodes
    ds_seeds() {
        local me="$1"
        local seeds=()
        for i in $(seq 1 "$n"); do
            [[ "$i" == "$me" ]] && continue
            seeds+=("datashuttle-${i}:7946")
        done
        IFS=','; echo "${seeds[*]+"${seeds[*]}"}"; unset IFS
    }

    {
        echo "# Auto-generated by demo.sh — do not edit manually"
        echo "# SHARDS=$n"
        echo "services:"

        # Active ClickHouse nodes — mount the N-shard cluster config
        for i in $(seq 1 "$n"); do
            echo "  clickhouse-${i}:"
            echo "    volumes:"
            echo "      - ./${xml_basename}:/etc/clickhouse-server/config.d/cluster.xml:ro"
        done

        # Disabled ClickHouse nodes — run a no-op sleep so Docker considers
        # them "running" (not failed). depends_on with service_started below
        # means nobody blocks on their healthcheck.
        if [[ $((n + 1)) -le 3 ]]; then
        for i in $(seq $((n + 1)) 3); do
            echo "  clickhouse-${i}:"
            echo "    entrypoint: [\"/bin/sh\", \"-c\", \"echo 'shard ${i} disabled (SHARDS=${n})' && sleep infinity\"]"
            echo "    healthcheck:"
            echo "      disable: true"
        done
        fi

        # clickhouse-init: wait only for active CH nodes (healthy) +
        # disabled CH nodes (service_started — they never become healthy).
        echo "  clickhouse-init:"
        echo "    depends_on:"
        for i in $(seq 1 "$n"); do
            echo "      clickhouse-${i}:"
            echo "        condition: service_healthy"
        done
        if [[ $((n + 1)) -le 3 ]]; then
        for i in $(seq $((n + 1)) 3); do
            echo "      clickhouse-${i}:"
            echo "        condition: service_started"
        done
        fi
        # Override the init command for the right set of hosts
        local hosts_list
        hosts_list=$(seq 1 "$n" | xargs -I{} echo "clickhouse-{}" | tr '\n' ' ')
        echo "    command:"
        echo "      - |"
        echo "        set -e"
        echo "        echo '=== Creating tables on ${n} shard(s) ==='"
        for i in $(seq 1 "$n"); do
            echo "        echo '  Creating local tables on clickhouse-${i}...'"
            echo "        clickhouse-client --host clickhouse-${i} --database analytics --multiquery < /init/init-local.sql"
        done
        echo "        echo '=== Creating distributed tables on coordinator ==='"
        echo "        clickhouse-client --host clickhouse-1 --database analytics --multiquery < /init/init-distributed.sql"
        echo "        echo '=== Seeding data via distributed tables ==='"
        echo "        clickhouse-client --host clickhouse-1 --database analytics --multiquery < /init/seed.sql"
        echo "        echo '=== Verifying shard distribution ==='"
        for i in $(seq 1 "$n"); do
            echo "        count=\$\$(clickhouse-client --host clickhouse-${i} --database analytics -q \"SELECT count() FROM events_local\")"
            echo "        echo \"  clickhouse-${i}: \$\$count rows in events_local\""
        done
        echo "        total=\$\$(clickhouse-client --host clickhouse-1 --database analytics -q \"SELECT count() FROM events\")"
        echo "        echo \"=== Total rows (distributed): \$\$total ===\""

        # Active DataShuttle nodes
        for i in $(seq 1 "$n"); do
            local seeds
            seeds="$(ds_seeds "$i")"
            echo "  datashuttle-${i}:"
            echo "    environment:"
            if [[ -n "$seeds" ]]; then
                echo "      DS_GOSSIP_SEEDS: \"${seeds}\""
            else
                echo "      DS_GOSSIP_SEEDS: \"\""
            fi
            echo "      DS_CLUSTER_EXPECTED_NODES: \"${n}\""
        done

        # Disabled DataShuttle nodes
        if [[ $((n + 1)) -le 3 ]]; then
        for i in $(seq $((n + 1)) 3); do
            echo "  datashuttle-${i}:"
            echo "    entrypoint: [\"/bin/sh\", \"-c\", \"echo 'ds-node-${i} disabled (SHARDS=${n})' && sleep infinity\"]"
            echo "    healthcheck:"
            echo "      disable: true"
        done
        fi

    } > "$OVERRIDE_FILE"

    echo "$n"
}

compose_cmd() {
    if [[ -f "$OVERRIDE_FILE" ]]; then
        docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" "$@"
    else
        docker compose -f "$COMPOSE_FILE" "$@"
    fi
}

# Read current SHARDS from override file (for status/inject/etc after up)
current_shards() {
    if [[ -f "$OVERRIDE_FILE" ]]; then
        grep "^# SHARDS=" "$OVERRIDE_FILE" | cut -d= -f2 || echo "3"
    else
        echo "3"
    fi
}

# ── Wait helpers ──────────────────────────────────────────────────────

wait_for_healthy() {
    local service="$1" timeout="${2:-60}"
    for i in $(seq 1 "$timeout"); do
        local status
        status=$(compose_cmd ps "$service" --format '{{.Status}}' 2>/dev/null || echo "")
        [[ "$status" == *"healthy"* ]] && { log "$service healthy (${i}s)"; return 0; }
        sleep 1
    done
    err "$service not healthy after ${timeout}s"; return 1
}

wait_for_port() {
    local port="$1" label="$2" timeout="${3:-60}"
    for i in $(seq 1 "$timeout"); do
        nc -z localhost "$port" 2>/dev/null && { log "$label ready on port $port (${i}s)"; return 0; }
        sleep 1
    done
    err "$label failed to start on port $port after ${timeout}s"; return 1
}

ch() {
    curl -sf "http://${CH_HOST}:${CH_PORT}/?database=${CH_DB}" \
        --data-binary "$1" 2>/dev/null
}

# ── Commands ──────────────────────────────────────────────────────────

cmd_up() {
    local shards="${1:-${SHARDS:-3}}"
    validate_shards "$shards"
    generate_override "$shards" >/dev/null

    hdr "Starting ClickHouse Parallel Snapshot Demo (${shards} shard(s))"

    if ! docker image inspect datashuttle:local >/dev/null 2>&1; then
        hdr "Building datashuttle:local image (~3 min first time)"
        docker build -t datashuttle:local -f "$PROJECT_ROOT/docker/Dockerfile" "$PROJECT_ROOT"
        log "image built"
    else
        log "datashuttle:local image found"
    fi

    hdr "Infrastructure (${shards}×ClickHouse + ${shards}×DataShuttle + MinIO + Polaris)"
    compose_cmd up -d

    # Wait for active ClickHouse shards
    wait_for_healthy clickhouse-1 60
    for i in $(seq 2 "$shards"); do
        wait_for_healthy "clickhouse-${i}" 30
    done

    # Wait for MinIO and Polaris
    wait_for_healthy minio 15
    wait_for_healthy polaris 30

    log "waiting for cluster init (seeding data)..."
    local timeout=120
    for i in $(seq 1 "$timeout"); do
        local status
        status=$(compose_cmd ps clickhouse-init --format '{{.Status}}' 2>/dev/null || echo "")
        if [[ "$status" == *"Exited (0)"* ]] || [[ "$status" == *"exited (0)"* ]]; then
            log "cluster init complete (${i}s)"; break
        fi
        if [[ "$status" == *"Exited"* ]] && [[ "$status" != *"(0)"* ]]; then
            err "clickhouse-init failed — run: ./demo.sh logs-init"
            exit 1
        fi
        sleep 1
    done

    # Wait for DataShuttle nodes
    wait_for_port "$DS_API_PORT" "DataShuttle node-1" 60
    for i in $(seq 2 "$shards"); do
        local port=$((8079 + i))
        wait_for_port "$port" "DataShuttle node-${i}" 30
    done

    hdr "Shuttle"
    local api="http://localhost:${DS_API_PORT}/api/v1/sql"
    local ct='Content-Type: application/json'

    # Wait for the SQL endpoint to actually accept writes — not just /version.
    # Empirically the registry takes a beat after /version returns OK.
    log "waiting for SQL endpoint to be writable..."
    local ready=0
    for i in $(seq 1 30); do
        local resp
        resp=$(curl -sf -X POST "$api" -H "$ct" \
            -d '{"sql": "SHOW CONNECTIONS"}' 2>&1) && { ready=1; break; }
        sleep 1
    done
    if [[ $ready -eq 0 ]]; then
        err "DataShuttle SQL endpoint not ready after 30s"
        return 1
    fi
    log "SQL endpoint ready (${i}s)"

    # ds_sql <name> <sql> — POST one statement, fail loudly on error.
    # Exit code reflects HTTP status; body is captured on failure.
    ds_sql() {
        local name="$1" sql="$2"
        local body
        body=$(printf '{"sql": %s}' "$(printf '%s' "$sql" | python3 -c \
            'import sys, json; print(json.dumps(sys.stdin.read()))')")
        local resp http
        resp=$(curl -s -w '\n%{http_code}' -X POST "$api" -H "$ct" -d "$body")
        http=$(echo "$resp" | tail -1)
        local body_json
        body_json=$(echo "$resp" | sed '$d')
        if [[ "$http" == "200" ]]; then
            log "$name OK"
            return 0
        fi
        # Idempotency: "already exists" is fine on re-run
        if echo "$body_json" | grep -qi "already exists\|duplicate"; then
            log "$name exists (skipped)"
            return 0
        fi
        err "$name failed (HTTP $http): $body_json"
        return 1
    }

    ds_sql "connection clickhouse_cluster" \
        "CREATE CONNECTION clickhouse_cluster TYPE CLICKHOUSE WITH (host = 'clickhouse-1', port = '8123', database = 'analytics', username = 'default', cluster = 'analytics_cluster')" \
        || return 1

    ds_sql "shuttle ch_parallel_events" \
        "CREATE SHUTTLE ch_parallel_events SOURCE clickhouse_cluster SCHEMA analytics TABLE events TARGET warehouse.clickhouse WITH (schedule = 'every 5 minutes', batch_size = '500000')" \
        || return 1

    ds_sql "shuttle ch_parallel_sessions" \
        "CREATE SHUTTLE ch_parallel_sessions SOURCE clickhouse_cluster SCHEMA analytics TABLE sessions TARGET warehouse.clickhouse WITH (schedule = 'every 5 minutes', batch_size = '500000')" \
        || return 1

    ds_sql "resume ch_parallel_events"   "RESUME SHUTTLE ch_parallel_events"   || return 1
    ds_sql "resume ch_parallel_sessions" "RESUME SHUTTLE ch_parallel_sessions" || return 1

    hdr "Demo Running (${shards} shard(s))"
    echo ""
    echo -e "  ${BOLD}DataShuttle UI${NC}   http://localhost:${DS_API_PORT}  (node-1, primary)"
    for i in $(seq 2 "$shards"); do
        local port=$((8079 + i))
        echo -e "  ${BOLD}DataShuttle${NC}      http://localhost:${port}            (node-${i})"
    done
    echo -e "  ${BOLD}MinIO Console${NC}    http://localhost:9001  (minioadmin/minioadmin)"
    echo -e "  ${BOLD}ClickHouse-1${NC}     http://localhost:${CH_PORT}  (coordinator)"
    for i in $(seq 2 "$shards"); do
        local port=$((8122 + i))
        echo -e "  ${BOLD}ClickHouse-${i}${NC}     http://localhost:${port}"
    done
    echo ""
    echo -e "  Inject:  ${BOLD}./demo.sh inject [table] [rows]${NC}"
    echo -e "  Status:  ${BOLD}./demo.sh status${NC}"
    echo -e "  Stop:    ${BOLD}./demo.sh down${NC}"
    echo -e "  Clean:   ${BOLD}./demo.sh clean${NC}"
    echo -e "  Logs:    ${BOLD}./demo.sh logs${NC}"
    echo ""
}

cmd_down() {
    hdr "Stopping Demo"
    compose_cmd stop 2>/dev/null || true
    log "all stopped"
}

cmd_clean() {
    hdr "Cleaning Demo (destroying all data)"
    compose_cmd down -v 2>/dev/null || true
    rm -f "$OVERRIDE_FILE" "$SCRIPT_DIR"/.cluster-config-*.xml
    log "volumes and generated configs removed"
}

cmd_status() {
    local shards
    shards="$(current_shards)"
    hdr "Demo Status (${shards} shard(s))"

    echo -e "\n${BOLD}Docker:${NC}"
    compose_cmd ps --format "  {{.Name}}\t{{.Status}}" 2>/dev/null \
        || echo "  (not running)"

    echo -e "\n${BOLD}Shuttles:${NC}"
    for p in ch_parallel_events ch_parallel_sessions; do
        local state
        state=$(curl -sf "http://localhost:${DS_API_PORT}/api/v1/shuttles/${p}" 2>/dev/null \
            | python3 -c "import sys,json;print(json.load(sys.stdin)['state'])" 2>/dev/null || echo "unreachable")
        echo "  $p: $state"
    done

    echo -e "\n${BOLD}ClickHouse shard row counts:${NC}"
    for i in $(seq 1 "$shards"); do
        local port=$((8122 + i))
        local count
        count=$(curl -sf "http://${CH_HOST}:${port}/?database=${CH_DB}" \
            --data-binary "SELECT count() FROM events_local" 2>/dev/null || echo "?")
        echo "  clickhouse-${i} (port ${port}): ${count} events_local rows"
    done

    local total
    total=$(ch "SELECT count() FROM events" 2>/dev/null || echo "?")
    echo "  total distributed: ${total} events"
    echo ""
}

cmd_inject() {
    local table="events" rows=10000

    case $# in
        0) ;;
        1) [[ "$1" =~ ^[0-9]+$ ]] && rows="$1" || table="$1" ;;
        2) table="$1"; rows="$2" ;;
        *) err "Usage: inject [table] [rows]"; exit 1 ;;
    esac

    local shards
    shards="$(current_shards)"
    hdr "Injecting into ${table} (${rows} rows across ${shards} shard(s))"

    ch "SELECT 1" >/dev/null 2>&1 \
        || { err "ClickHouse unreachable — run ./demo.sh up first"; exit 1; }

    local max_id
    max_id=$(ch "SELECT COALESCE(max(id), 0) FROM ${table}" 2>/dev/null || echo "0")

    case "$table" in
        events)
            log "inserting $rows events via distributed table (auto-sharded)..."
            ch "
INSERT INTO events (id, session_id, user_id, event_type, event_name, page_url,
                    referrer, properties, region, device_type, event_time)
SELECT
    ${max_id} + number + 1,
    (number % 20000) + 1,
    (number % 5000) + 1,
    arrayElement(['page_view','click','search','purchase','signup',
                  'add_to_cart','remove_from_cart','checkout'], (number % 8) + 1),
    concat(arrayElement(['page_view','click','search','purchase','signup',
                         'add_to_cart','remove_from_cart','checkout'], (number % 8) + 1),
           '_', toString((number % 100) + 1)),
    concat('https://example.com/',
           arrayElement(['home','products','pricing','about','blog','docs',
                         'signup','checkout','search','profile'], (number % 10) + 1)),
    if(number % 4 = 0,
       arrayElement(['https://google.com','https://facebook.com',
                     'https://twitter.com',''], (number % 4) + 1), NULL),
    concat('{\"button\":\"btn_', toString(number % 50), '\",\"value\":', toString((number * 13) % 1000), '}'),
    arrayElement(['us-east','us-west','eu-west','eu-central','ap-south','ap-east'], (number % 6) + 1),
    arrayElement(['desktop','mobile','tablet'], (number % 3) + 1),
    now64(3) - toIntervalSecond(number * 2)
FROM numbers($rows)
" && log "inserted $rows events"
            ;;

        sessions)
            log "inserting $rows sessions..."
            ch "
INSERT INTO sessions (id, user_id, session_start, session_end,
                      duration_sec, page_count, device_type, country, is_bounce)
SELECT
    ${max_id} + number + 1,
    (number % 5000) + 1,
    now64(3) - toIntervalSecond(number * 30),
    now64(3) - toIntervalSecond(number * 30) + toIntervalSecond(60 + (number * 7) % 1800),
    60 + (number * 7) % 1800,
    1 + (number % 20),
    arrayElement(['desktop','mobile','tablet'], (number % 3) + 1),
    arrayElement(['US','GB','DE','FR','CA','AU','JP','BR'], (number % 8) + 1),
    (number % 5) = 0
FROM numbers($rows)
" && log "inserted $rows sessions"
            ;;

        users)
            log "inserting $rows users..."
            ch "
INSERT INTO users (id, username, email, full_name, country, city,
                   plan, signup_date, last_login_at, is_active)
SELECT
    ${max_id} + number + 1,
    concat('user_', toString(${max_id} + number + 1)),
    concat('user_', toString(${max_id} + number + 1), '@example.com'),
    concat(
        arrayElement(['Alice','Bob','Carol','Dan','Eve','Frank','Grace','Hank','Ivy','Jack'], (number % 10) + 1),
        ' ',
        arrayElement(['Smith','Jones','Lee','Kim','Patel','Chen','Brown','Davis','Wilson','Moore'], (number % 10) + 1)
    ),
    arrayElement(['US','GB','DE','FR','CA','AU','JP','BR','IN','MX'], (number % 10) + 1),
    arrayElement(['NYC','London','Berlin','Paris','Toronto','Sydney','Tokyo','São Paulo'], (number % 8) + 1),
    arrayElement(['free','starter','pro','enterprise'], (number % 4) + 1),
    today() - toIntervalDay(number % 365),
    now64(3) - toIntervalHour(number % 720),
    (number % 10) != 0
FROM numbers($rows)
" && log "inserted $rows users"
            ;;

        *)
            err "Unknown table: $table"
            err "Valid: events, sessions, users"
            exit 1
            ;;
    esac

    echo ""
    local shards
    shards="$(current_shards)"
    log "distribution after inject:"
    for i in $(seq 1 "$shards"); do
        local port=$((8122 + i))
        local count
        count=$(curl -sf "http://${CH_HOST}:${port}/?database=${CH_DB}" \
            --data-binary "SELECT count() FROM ${table}_local" 2>/dev/null || echo "?")
        echo "  shard ${i}: ${count} ${table}_local rows"
    done
    echo ""
    log "trigger shuttle: ./demo.sh resume  — or wait for next scheduled run"
}

cmd_resume() {
    hdr "Triggering shuttles"
    local api="http://localhost:${DS_API_PORT}/api/v1/sql"
    local ct='Content-Type: application/json'
    for p in ch_parallel_events ch_parallel_sessions; do
        curl -sf -X POST "$api" -H "$ct" \
            -d "{\"sql\": \"PAUSE SHUTTLE ${p}\"}" >/dev/null 2>&1 || true
        sleep 1
        curl -sf -X POST "$api" -H "$ct" \
            -d "{\"sql\": \"RESUME SHUTTLE ${p}\"}" >/dev/null 2>&1 || true
        log "$p restarted"
    done
}

cmd_logs() {
    hdr "DataShuttle node-1 Logs"
    compose_cmd logs -f datashuttle-1 2>/dev/null \
        || err "datashuttle-1 not running"
}

cmd_logs_init() {
    hdr "ClickHouse Init Logs"
    compose_cmd logs clickhouse-init 2>/dev/null \
        || err "clickhouse-init not found"
}

cmd_open() {
    if command -v open &>/dev/null; then open "http://localhost:${DS_API_PORT}"
    elif command -v xdg-open &>/dev/null; then xdg-open "http://localhost:${DS_API_PORT}"
    else log "Open http://localhost:${DS_API_PORT}"; fi
}

cmd_restart() {
    local shards="${1:-$(current_shards)}"
    cmd_down
    sleep 2
    cmd_up "$shards"
}

# ── Dispatch ──────────────────────────────────────────────────────────

case "${1:-help}" in
    up)      shift; cmd_up "$@" ;;
    down)    cmd_down ;;
    clean)   cmd_clean ;;
    status)  cmd_status ;;
    restart) shift; cmd_restart "$@" ;;
    inject)  shift; cmd_inject "$@" ;;
    resume)  cmd_resume ;;
    logs)    cmd_logs ;;
    logs-init) cmd_logs_init ;;
    open)    cmd_open ;;
    *)
        echo "Usage: $0 <command> [args]"
        echo ""
        echo "Commands:"
        echo "  up [shards]             Start demo (shards: 1, 2, or 3; default: 3)"
        echo "  down                    Stop all containers (keep data)"
        echo "  clean                   Stop + destroy all volumes and generated configs"
        echo "  status                  Show containers, shuttles, shard row counts"
        echo "  restart [shards]        down + up [shards]"
        echo "  inject                  Insert 10000 events (auto-sharded)"
        echo "  inject <n>              Insert <n> events"
        echo "  inject <table> <n>      Insert <n> rows into specific table"
        echo "                          Tables: events, sessions, users"
        echo "  resume                  Manually trigger shuttles (after inject)"
        echo "  logs                    Tail DataShuttle node-1 logs"
        echo "  logs-init               Show ClickHouse init container logs"
        echo "  open                    Open DataShuttle UI in browser"
        echo ""
        echo "Examples:"
        echo "  ./demo.sh up            # 3-shard cluster (default)"
        echo "  ./demo.sh up 1          # single-node, minimal resources"
        echo "  ./demo.sh up 2          # 2-shard cluster"
        echo "  SHARDS=1 ./demo.sh up   # same as ./demo.sh up 1"
        exit 1
        ;;
esac
